### ISSUE TITLE
Publication Process V1.0 - namespace url pattern is incorrect

### ISSUE THREAD

**Issue by chet-ensign** [niemopen/ntac-admin#46]
3.1 Artifact identifiers (https://github.com/niemopen/ntac-admin/blob/main/project-notes/docs/niem-pubs-v1.0-pn01/niem-pubs-v1.0-pn01.md#31-artifact-identifiers) reads "SHOULD use **https://docs.oasis-open.org/ns/niemopen** as the root URI for resolvability." 

I don't believe that is correct. The namespace url would use docs.oasis-open.org/niemopen/ns. Also the url docs.oasis-open.org/niemopen is where all approved work will be published. 

Please double-check with paul.knight@oasis-open.org

**Comment by cdmgtri** [comment]
Thanks!  I've sent an email to confirm.  Also found this:


> An XML namespace name identified by an HTTP scheme URI reference must conform to the pattern:
>
> http://docs.oasis-open.org/[tc-shortname]/ns/xxxx

http://docs.oasis-open.org/specGuidelines/ndr/namingDirectives.html#xml-namespaces

**Comment by cdmgtri** [comment]
Received guidance from Paul that the next edition of the Naming Directives will recommend the use of https.  

Updated the NIEM pattern to start with https://docs.oasis-open.org/niemopen/ns/.

See 00c4d05c356fb50857f630772b883703142a3417 for changes.
