### ISSUE TITLE
Publication Process V1.0 - some SHOULDs should be MUST

### ISSUE THREAD

**Issue by chet-ensign** [niemopen/ntac-admin#47]
I see places where I'd expect MUST instead of SHOULD. For example, 5.7.2 Approval process starts "The PGB SHOULD notify the NIEMOpen community via the project mailing list at least 14 days in advance..." That requirement is a MUST because it is required by the rules. SHOULD suggest that there's an option not to do it.

**Comment by cdmgtri** [comment]
Project note has been updated with the given example.  Thanks!
