### ISSUE TITLE
Publication Process V1.0 - grammatical error

### ISSUE THREAD

**Issue by chet-ensign** [niemopen/ntac-admin#48]
The first bullet in 5.7.2 has a grammatical error: "The PGB SHOULD notify the NIEMOpen community via the project mailing list at least 14 days in advance >> once they have decided to are ready to << initiate a PGB vote or consensus call on the nominated PSD. Looks like an edit wasn't completed.

**Comment by cdmgtri** [comment]
Project note has been updated.  Thanks!
