### ISSUE TITLE
Publication Process V1.0 - suggested rewording

### ISSUE THREAD

**Issue by chet-ensign** [niemopen/ntac-admin#50]
5.8.1 Recommendation for approval 

Sixth bullet reads "list of non-material changes, if the submission is not already an approved PSD" - This confused me at first. I suggest editing to read "list of non-material changes made since the last approved PSD along with an affirmation from the TSC that they judge the changes non-material" - I think that is what's meant

**Comment by cdmgtri** [comment]
Project note has been updated.  Thanks!
